// file: /pages/index.js
import Head from "next/head";
import Chat from "@/components/Chat";

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS OpenAI Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Chat/>
      </main>
    </>
  );
}
